import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { MeetingRecord } from "../types";

export const generateMomPdf = (record: MeetingRecord) => {
  const doc = new jsPDF();
  const themeColor = [30, 58, 138]; // Blue-900

  // --- Header ---
  doc.setFontSize(22);
  doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
  doc.text("Minutes of Meeting", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by AutoMoM | ${new Date().toLocaleDateString()}`, 14, 26);

  // Line separator
  doc.setDrawColor(200);
  doc.line(14, 30, 196, 30);

  // --- Info Block ---
  doc.setFontSize(11);
  doc.setTextColor(0);
  
  let y = 40;
  
  // Left Column
  doc.setFont(undefined, 'bold');
  doc.text("Supplier Details:", 14, y);
  doc.setFont(undefined, 'normal');
  doc.text(`${record.supplierName} (${record.supplierCode})`, 14, y + 6);
  
  // Right Column
  doc.setFont(undefined, 'bold');
  doc.text("Meeting Date:", 120, y);
  doc.setFont(undefined, 'normal');
  doc.text(record.date, 120, y + 6);

  y += 20;

  // --- Executive Summary ---
  if (record.executiveSummary) {
    doc.setFillColor(241, 245, 249); // slate-100
    doc.rect(14, y - 5, 182, 0, 'F'); // Just setting background if we knew height, but simple text is easier for now
    
    doc.setFont(undefined, 'bold');
    doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.text("Executive Summary", 14, y);
    y += 7;
    
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50);
    const splitText = doc.splitTextToSize(record.executiveSummary, 182);
    doc.text(splitText, 14, y);
    y += splitText.length * 5 + 10;
  }

  // --- Participants Table ---
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
  doc.text("Participants", 14, y);
  y += 4;

  const participantRows = record.participants.map(p => [
    p.name, 
    p.designation, 
    p.type === 'CUSTOMER' ? 'Customer' : 'Supplier',
    p.email || '-' 
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Name', 'Designation', 'Team', 'Email']],
    body: participantRows,
    theme: 'striped',
    headStyles: { fillColor: themeColor as any },
    styles: { fontSize: 9 },
    margin: { left: 14, right: 14 },
  });

  // Get final Y from previous table
  y = (doc as any).lastAutoTable.finalY + 15;

  // --- Observations Table ---
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
  doc.text("Observations & Action Plan", 14, y);
  y += 4;

  const obsRows = record.observations.map((obs, index) => [
    index + 1,
    obs.category,
    obs.polishedDescription || obs.description,
    obs.responsibility || '-',
    obs.targetDate || '-',
    obs.status,
    '' // Photo placeholder
  ]);

  autoTable(doc, {
    startY: y,
    head: [['#', 'Category', 'Observation', 'Resp.', 'Target', 'Status', 'Photo']],
    body: obsRows,
    theme: 'grid',
    headStyles: { fillColor: themeColor as any },
    bodyStyles: { minCellHeight: 20, valign: 'middle' },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 25 },
      2: { cellWidth: 60 },
      3: { cellWidth: 25 },
      4: { cellWidth: 20 },
      5: { cellWidth: 18 },
      6: { cellWidth: 24 }
    },
    didDrawCell: (data) => {
      if (data.section === 'body' && data.column.index === 6) {
        // Photo column
        const obs = record.observations[data.row.index];
        if (obs.photoDataUrl) {
           try {
             // Add image inside cell
             const x = data.cell.x + 2;
             const y = data.cell.y + 2;
             const w = 20;
             const h = 16;
             doc.addImage(obs.photoDataUrl, 'JPEG', x, y, w, h);
           } catch(e) {
             console.error('Err adding image', e);
           }
        }
      }
    }
  });

  // --- Footer (Manual pagination if needed, but jspdf-autotable handles page breaks) ---
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
  }

  doc.save(`MoM_${record.supplierCode}_${record.date}.pdf`);
};
